### ISSUE TITLE
现在update_chunzhen.py还能用吗？

### ISSUE THREAD

**Issue by rltyty** [out0fmemory/qqwry.dat#12]
执行脚本返回-1，按脚本里的地址，wget 报错HTTP request sent, awaiting response... 503 Service Temporarily Unavailable

但是浏览器可以下载copywrite.rar 和 qqwry.rar。

**Comment by rltyty** [comment]
可能是因为用cloudflare保护的原因，必须启用cookie和js才能通过。所以这个脚本暂时用不了了

**Comment by rltyty** [comment]
现在地址在”纯真IP实验室“微信公众号定期更新了。

**Comment by rltyty** [comment]
类似这种含有随机字符串的地址，http://cz88.net/soft/zh84ww-2022-05-18.zip

**Comment by QGB** [comment]
https://cz88.net/soft/77Q9jSb5-2024-03-13.zip
