### ISSUE TITLE
数据库文件为空

### ISSUE THREAD

**Issue by acgrid** [out0fmemory/qqwry.dat#8]
https://github.com/out0fmemory/qqwry.dat/blob/3b0008f2115c1506c36d06eb72ba1a3c5c56089c/qqwry_lastest.dat
0 bytes

**Comment by out0fmemory** [comment]
> https://github.com/out0fmemory/qqwry.dat/blob/3b0008f2115c1506c36d06eb72ba1a3c5c56089c/qqwry_lastest.dat
> 0 bytes

fixed
